local paq = require'paq-nvim'.paq
paq {'savq/paq-nvim', opt=true}
paq 'akinsho/nvim-bufferline.lua'
paq 'jalvesaq/vimcmdline'
paq 'chrisbra/Colorizer'
paq 'nvim-lua/completion-nvim'
paq 'steelsojka/completion-buffers'
paq 'mfussenegger/nvim-dap'
paq 'mfussenegger/nvim-dap-python'
paq 'theHamsta/nvim-dap-virtual-text'
paq 'Konfekt/FastFold'
paq 'tpope/vim-fugitive'
paq 'rhysd/vim-grammarous'
paq 'sjl/gundo.vim'
paq 'Yggdroot/indentLine'
paq 'neovim/nvim-lspconfig'
paq 'nvim-lua/lsp-status.nvim'
paq 'Shougo/neosnippet.vim'
paq 'scrooloose/nerdcommenter'
paq 'Vimjas/vim-python-pep8-indent'
paq 'goldfeld/vim-seek'
paq 'nightsense/snow'
paq 'tmhedberg/SimpylFold'
-- telescope and its support
paq 'nvim-lua/popup.nvim'
paq 'nvim-lua/plenary.nvim'
paq 'luochen1990/rainbow'
paq 'nvim-telescope/telescope.nvim'
paq 'kyazdani42/nvim-tree.lua'
paq {'nvim-treesitter/nvim-treesitter', hook=vim.fn["TSUpdate"]}
paq 'p00f/nvim-ts-rainbow'
paq 'roxma/nvim-yarp'
paq 'kyazdani42/nvim-web-devicons'
