local paq = require'paq-nvim'.paq
paq {'savq/paq-nvim', opt=true}
paq 'akinsho/nvim-bufferline.lua'
paq 'jalvesaq/vimcmdline'
paq 'norcalli/nvim-colorizer.lua'
paq 'nvim-lua/completion-nvim'
paq 'steelsojka/completion-buffers'
paq 'mfussenegger/nvim-dap'
paq 'mfussenegger/nvim-dap-python'
paq 'tpope/vim-fugitive'
paq 'rhysd/vim-grammarous'
paq 'sjl/gundo.vim'
paq 'yuntan/neovim-indent-guides'
paq 'neovim/nvim-lspconfig'
paq 'nvim-lua/lsp-status.nvim'
paq 'Shougo/neosnippet.vim'
paq 'scrooloose/nerdcommenter'
-- paq 'Vimjas/vim-python-pep8-indent'
paq 'goldfeld/vim-seek'
paq 'nightsense/snow'
-- telescope and its support
paq 'nvim-lua/popup.nvim'
paq 'nvim-lua/plenary.nvim'
paq 'nvim-telescope/telescope.nvim'
paq 'nvim-telescope/telescope-dap.nvim'
paq 'nvim-treesitter/nvim-treesitter'
paq 'nvim-treesitter/nvim-treesitter-refactor'
paq 'p00f/nvim-ts-rainbow'
paq 'kyazdani42/nvim-web-devicons'
