local paq = require'paq-nvim'.paq
paq {'savq/paq-nvim', opt=true}
paq 'akinsho/nvim-bufferline.lua'
paq 'jalvesaq/vimcmdline'
paq 'chrisbra/Colorizer'
paq 'nvim-lua/completion-nvim'
paq 'steelsojka/completion-buffers'
paq 'tpope/vim-fugitive'
paq 'rhysd/vim-grammarous'
paq 'glepnir/galaxyline.nvim'
paq 'sjl/gundo.vim'
paq 'Yggdroot/indentLine'
paq 'neovim/nvim-lspconfig'
paq 'glepnir/lspsaga.nvim'
paq 'nvim-lua/lsp-status.nvim'
paq 'Shougo/neosnippet.vim'
paq 'scrooloose/nerdcommenter'
paq 'arcticicestudio/nord-vim'
paq 'Vimjas/vim-python-pep8-indent'
paq 'goldfeld/vim-seek'
-- telescope and its support
paq 'nvim-lua/popup.nvim'
paq 'nvim-lua/plenary.nvim'
paq 'luochen1990/rainbow'
paq 'nvim-telescope/telescope.nvim'
paq 'roxma/nvim-yarp'
paq 'kyazdani42/nvim-web-devicons'
